package com.dating.recommendation.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Period;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * ============================================================================
 * USER ENTITY - FOR RECOMMENDATION SERVICE
 * ============================================================================
 *
 * PURPOSE:
 * JPA entity representing a user for recommendation calculations.
 * This is a read-only view of user data from the User Service database.
 *
 * NOTE:
 * The User Service is the source of truth for user data. This entity
 * mirrors the users table for read-only access by the Recommendation Service.
 *
 * FIELDS USED BY SCORERS:
 * - Age scorer: dateOfBirth (calculated age), minAgePreference, maxAgePreference
 * - Location scorer: latitude, longitude, maxDistancePreference
 * - Interest scorer: interests (Set<String>)
 * - Activity scorer: lastActiveAt
 * - Gender scorer: gender, genderPreferences
 *
 * DATABASE MAPPING:
 * - Table: users (shared with User Service)
 * - Primary key: id (UUID)
 * - Preferences: Embedded or separate table (user_preferences)
 *
 * ============================================================================
 */
@Entity
@Table(name = "users")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    // =========================================================================
    // PRIMARY KEY
    // =========================================================================

    /**
     * Unique identifier for the user.
     * Generated by User Service when user registers.
     */
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    // =========================================================================
    // BASIC PROFILE INFORMATION
    // =========================================================================

    /**
     * User's email address (unique).
     * Used for authentication and communication.
     */
    @Column(name = "email", nullable = false, unique = true)
    private String email;

    /**
     * Display name chosen by user.
     * Shown to other users in recommendations and matches.
     */
    @Column(name = "username")
    private String username;

    /**
     * User's first name.
     * Shown in profile and recommendations.
     */
    @Column(name = "first_name")
    private String firstName;

    /**
     * User's last name.
     * May be hidden based on privacy settings.
     */
    @Column(name = "last_name")
    private String lastName;

    // =========================================================================
    // DEMOGRAPHICS - USED BY AGE SCORER
    // =========================================================================

    /**
     * User's date of birth.
     * Used to calculate age for age compatibility scoring.
     *
     * SCORER USAGE:
     * AgeCompatibilityScorer uses this to check if candidate falls
     * within user's preferred age range and vice versa.
     */
    @Column(name = "date_of_birth", nullable = false)
    private LocalDate dateOfBirth;

    /**
     * User's gender identity.
     * Values: MALE, FEMALE, OTHER
     *
     * SCORER USAGE:
     * GenderPreferenceScorer checks if this matches the other user's
     * genderPreferences setting.
     */
    @Column(name = "gender", nullable = false)
    private String gender;

    // =========================================================================
    // LOCATION - USED BY LOCATION SCORER
    // =========================================================================

    /**
     * User's latitude coordinate.
     * Updated when user's location changes.
     *
     * SCORER USAGE:
     * LocationScorer uses this with longitude to calculate distance
     * using the Haversine formula.
     */
    @Column(name = "latitude")
    private Double latitude;

    /**
     * User's longitude coordinate.
     * Updated when user's location changes.
     */
    @Column(name = "longitude")
    private Double longitude;

    /**
     * City name for display purposes.
     * Not used in scoring, only for UI display.
     */
    @Column(name = "city")
    private String city;

    /**
     * Country name for display purposes.
     * Not used in scoring, only for UI display.
     */
    @Column(name = "country")
    private String country;

    // =========================================================================
    // PROFILE CONTENT
    // =========================================================================

    /**
     * User's bio/description.
     * Can be used for future text-based matching.
     */
    @Column(name = "bio", columnDefinition = "TEXT")
    private String bio;

    /**
     * URL to user's primary photo.
     * Used in recommendation cards.
     */
    @Column(name = "photo_url")
    private String photoUrl;

    // =========================================================================
    // PREFERENCES - USED BY MULTIPLE SCORERS
    // =========================================================================

    /**
     * Minimum age of potential matches (inclusive).
     * Default: 18 (legal minimum)
     *
     * SCORER USAGE:
     * AgeCompatibilityScorer checks if candidate's age >= this value.
     */
    @Column(name = "min_age_preference")
    @Builder.Default
    private Integer minAgePreference = 18;

    /**
     * Maximum age of potential matches (inclusive).
     * Default: 100 (effectively no limit)
     *
     * SCORER USAGE:
     * AgeCompatibilityScorer checks if candidate's age <= this value.
     */
    @Column(name = "max_age_preference")
    @Builder.Default
    private Integer maxAgePreference = 100;

    /**
     * Maximum distance for potential matches in kilometers.
     * Default: 50km
     *
     * SCORER USAGE:
     * LocationScorer uses this to normalize distance scores.
     * Candidates beyond this distance get score 0.0.
     */
    @Column(name = "max_distance_preference")
    @Builder.Default
    private Integer maxDistancePreference = 50;

    /**
     * Genders this user is interested in.
     * Stored as comma-separated values: "MALE,FEMALE" or single value.
     *
     * SCORER USAGE:
     * GenderPreferenceScorer checks if candidate's gender is in this set.
     *
     * HOW TO MODIFY:
     * If you need more sophisticated gender preferences, convert this
     * to a @ManyToMany relationship with a GenderPreference entity.
     */
    @ElementCollection
    @CollectionTable(name = "user_gender_preferences",
                     joinColumns = @JoinColumn(name = "user_id"))
    @Column(name = "gender")
    @Builder.Default
    private Set<String> genderPreferences = new HashSet<>();

    // =========================================================================
    // INTERESTS - USED BY INTEREST SCORER
    // =========================================================================

    /**
     * User's interests/hobbies.
     * Stored as a set of strings: ["hiking", "cooking", "travel"]
     *
     * SCORER USAGE:
     * InterestScorer calculates Jaccard similarity between user's
     * interests and candidate's interests.
     *
     * HOW TO MODIFY:
     * - Add interest categories (sports, music, food)
     * - Add interest weights (primary vs secondary interests)
     * - Use NLP to match similar interests ("running" ≈ "jogging")
     */
    @ElementCollection
    @CollectionTable(name = "user_interests",
                     joinColumns = @JoinColumn(name = "user_id"))
    @Column(name = "interest")
    @Builder.Default
    private Set<String> interests = new HashSet<>();

    // =========================================================================
    // ACTIVITY TRACKING - USED BY ACTIVITY SCORER
    // =========================================================================

    /**
     * When the user was last active on the platform.
     * Updated on login, swipe, message, profile view.
     *
     * SCORER USAGE:
     * ActivityScorer uses this to prefer active users who are
     * more likely to respond to matches.
     */
    @Column(name = "last_active_at")
    private LocalDateTime lastActiveAt;

    /**
     * Whether the user's email/phone is verified.
     * Can be used as a scoring boost factor.
     */
    @Column(name = "verified")
    @Builder.Default
    private Boolean verified = false;

    /**
     * Whether the user account is active.
     * Inactive users should be excluded from recommendations.
     */
    @Column(name = "active")
    @Builder.Default
    private Boolean active = true;

    // =========================================================================
    // TIMESTAMPS
    // =========================================================================

    /**
     * When the user account was created.
     * Can be used for "new user" boosts in recommendations.
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * When the user profile was last updated.
     * Trigger for cache invalidation.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // =========================================================================
    // HELPER METHODS
    // =========================================================================

    /**
     * Calculate user's current age from date of birth.
     *
     * @return Age in years
     */
    public int getAge() {
        if (dateOfBirth == null) {
            return 0;
        }
        return Period.between(dateOfBirth, LocalDate.now()).getYears();
    }

    /**
     * Check if user has location data set.
     *
     * @return true if both latitude and longitude are set
     */
    public boolean hasLocation() {
        return latitude != null && longitude != null;
    }

    /**
     * Check if user has any interests set.
     *
     * @return true if interests set is not empty
     */
    public boolean hasInterests() {
        return interests != null && !interests.isEmpty();
    }
}
